//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotx64Dbg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dotx64Dbg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Dotx64Dbg;
        ///
        ///public partial class MyPlugin : IPlugin, IHotload
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Called as soon the plugin is first loaded, consequent hot-loads will not call this again.
        ///	/// &lt;/summary&gt;
        ///    public MyPlugin()
        ///    {
        ///		Console.WriteLine(&quot;Hello World&quot;);
        ///    }
        ///
        ///	/// &lt;summary&gt;
        ///	/// This is called after construction. This is also only called once.
        ///	/// &lt;/summary&gt;
        ///    public void Startup()
        ///    {
        ///    }
        ///
        ///	/// &lt;summary&gt;
        ///	/// Classes that  have IHotload can implement this to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plugin_cs {
            get {
                return ResourceManager.GetString("plugin_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;%PLUGIN_NAME%&quot;,
        ///  &quot;Description&quot;: &quot;&quot;,
        ///  &quot;Version&quot;: &quot;0.0.0&quot;,
        ///  &quot;Author&quot;: &quot;&quot;,
        ///  &quot;Website&quot;: &quot;&quot;
        ///}
        ///.
        /// </summary>
        internal static string plugin_json {
            get {
                return ResourceManager.GetString("plugin_json", resourceCulture);
            }
        }
    }
}
